### ISSUE TITLE
Useraudit and Custom User model

### ISSUE THREAD

**Issue by dedayoa** [muccg/django-useraudit#12]
I stumbled upon useraudit and I've been enjoying using it. However, for this project, I had to implement a custom user model - extending AbstractBaseUser.
Rather than having a "username", this project requires a "phone_number" as the username, and this leads to useraudit not displaying anything in the username field (in admin), and not having any value stored for username in the db.

Is there a work around for this situation? I'm running Django 1.10.4
Regards,

**Comment by sztamas** [comment]
Hi,

Currently, that isn't supported.

Would setting up an alias property be acceptable for you?

    class YourCustomUser(AbstractBaseUser):
        ...
        @property
        def username(self):
            return self.phone_number
        ...

I think that should work, please let us know if there are any problems with it.

Cheers,

Tamas

**Comment by sztamas** [comment]
Closing this as it is pretty old now.
