### ISSUE TITLE
Failed login counter should be reset to 0 on successful login

### ISSUE THREAD

**Issue by sztamas** [muccg/django-useraudit#3]
Currently the failed logins are added up even if the user logged in successfully between failed logins.

The counter should count only consecutive failed logins, therefore should be reset to 0 on every successful login.

**Comment by sztamas** [comment]
This

**Comment by mradochonski** [comment]
```
def login_callback(sender, user, request, **kwargs):
    login_logger.log_login(user.get_username(), request)
    login_attempt_logger.reset(user.get_username())

# User logged in Django signal
user_logged_in.connect(login_callback)
```
```
def reset(self, username):
    defaults = {
       'count': 0,
       'timestamp': datetime.datetime.now()
    }
    LoginAttempt.objects.update_or_create(username=username, defaults=defaults)
```

**Comment by sztamas** [comment]
Yeah, but the Django handling is a bit inconsistent:

user_login_failed is sent when authenticate fails:

https://github.com/django/django/blob/094ea69e072779661d36e46a6caec0fea4b3ca16/django/contrib/auth/__init__.py#L85

user_logged_in, however is sent when login() is successful:

https://github.com/django/django/blob/094ea69e072779661d36e46a6caec0fea4b3ca16/django/contrib/auth/__init__.py#L130

:-(
