### ISSUE TITLE
NoReverseMatch at /admin/useraudit/loginattempt/

### ISSUE THREAD

**Issue by agusteam34** [muccg/django-useraudit#41]
When user is desactivate and there are a login attempt with this user:

NoReverseMatch at /admin/useraudit/loginattempt/
'useraudit' is not a registered namespace

I am using Django 2.2

**Comment by dev6rahul** [comment]
> When user is desactivate and there are a login attempt with this user:
> 
> NoReverseMatch at /admin/useraudit/loginattempt/
> 'useraudit' is not a registered namespace
> 
> I am using Django 2.2

hello ahusteam34 were you able to execute this on you app.
i am facing some problem on intergrating this with my app can you help

**Comment by geclick** [comment]
anyone fixed this??

**Comment by agusteam34** [comment]
Yes, It was necessary to add this in urls.py:
path(r'^ltw/',include('useraudit.urls',namespace="useraudit")),
